version: '3.7'

services:
        dashboard:
                image: getumbrel/dashboard
                build:
                  context: ../umbrel-dashboard
                  dockerfile: Dockerfile.dev
                volumes:
                  - ../umbrel-dashboard:/app
        manager:
                image: getumbrel/manager
                build: ../umbrel-manager
        middleware:
                image: getumbrel/middleware
                build: ../umbrel-middleware
